import type { LinkRole } from "#shared/types/affiliate";

/**
 * Everything the Overview and Links sections need, in one request.
 *
 * The affiliate is resolved from the session by requireAffiliate() and every
 * query below is filtered by that id. Nothing in this handler reads an
 * identifier from the request — see the note at the top of server/utils/auth.ts.
 */
export default defineEventHandler(async (event) => {
	const affiliate = await requireAffiliate(event);

	const dayOffset = (days: number) =>
		new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

	const today = dayOffset(0);
	const yesterday = dayOffset(1);
	const thirtyDaysAgo = dayOffset(30);
	const sixtyDaysAgo = dayOffset(60);

	// The heatmap and breakdowns behind the Overview highlights come from the
	// same RPC the Analytics tab uses, over a fixed 30-day window. Reused rather
	// than reimplemented here: PostgREST cannot group, so doing it in this
	// handler would mean pulling every visit row and counting them in memory —
	// which `db_max_rows` would silently truncate on a busy affiliate.
	const HIGHLIGHT_DAYS = 30;
	const timezone = canonicalTimezone(affiliate.timezone) ?? "UTC";

	const [
		todayVisits, yesterdayVisits,
		recentVisits, priorVisits,
		totalVisits, firstVisit, byDay,
		traffic,
	] = await Promise.all([
		db().from("referral_visits").select("*", { count: "exact", head: true })
			.eq("affiliate_id", affiliate.id).eq("day", today),

		// The comparison windows behind the trend under each figure. Counts, not
		// rows, so they are unaffected by the row cap that limits `byDay`.
		db().from("referral_visits").select("*", { count: "exact", head: true })
			.eq("affiliate_id", affiliate.id).eq("day", yesterday),

		db().from("referral_visits").select("*", { count: "exact", head: true })
			.eq("affiliate_id", affiliate.id).gte("day", thirtyDaysAgo),

		// The 30 days before that, so "vs last month" compares like with like.
		db().from("referral_visits").select("*", { count: "exact", head: true })
			.eq("affiliate_id", affiliate.id)
			.gte("day", sixtyDaysAgo).lt("day", thirtyDaysAgo),

		db().from("referral_visits").select("*", { count: "exact", head: true })
			.eq("affiliate_id", affiliate.id),

		db().from("referral_visits").select("occurred_at")
			.eq("affiliate_id", affiliate.id)
			.order("occurred_at", { ascending: true })
			.limit(1).maybeSingle(),

		db().from("referral_visits").select("day")
			.eq("affiliate_id", affiliate.id).gte("day", thirtyDaysAgo),

		db().rpc("affiliate_traffic", {
			p_affiliate_id: affiliate.id,
			p_since: new Date(Date.now() - HIGHLIGHT_DAYS * 24 * 60 * 60 * 1000).toISOString(),
			p_until: new Date().toISOString(),
			p_timezone: timezone,
		}),
	]);

	// Counted in memory rather than with a group-by: PostgREST has no grouping,
	// and 30 days of unique daily visits for one affiliate is a small set.
	const dailyCounts = new Map<string, number>();
	for (const row of byDay.data ?? []) {
		const day = row.day as string;
		dailyCounts.set(day, (dailyCounts.get(day) ?? 0) + 1);
	}

	const highlights = summarise(traffic.data);

	const onboarding = (affiliate.onboarding ?? {}) as Record<string, unknown>;

	// Derived from real state, not from a flag the affiliate could set. Only
	// "shared" is a recorded action, because copying a link leaves no trace.
	const steps = {
		liteTelegramAdded: Boolean(affiliate.lite_telegram_url),
		calendlyAdded: Boolean(affiliate.calendly_url),
		linkShared: onboarding.linkShared === true,
		firstVisitReceived: Boolean(firstVisit.data),
	};

	const completed = Object.values(steps).filter(Boolean).length;

	const link = (role: LinkRole, value: string | null) =>
		isAllowedLink(role, value) ? value : null;

	return {
		affiliate: {
			slug: affiliate.slug,
			displayName: affiliate.display_name,
			timezone: affiliate.timezone,
			memberSince: affiliate.created_at,
		},

		referralUrl: referralUrl(event, affiliate.slug),

		links: {
			// Generated by us from Whop during onboarding — the affiliate has no
			// field for this and cannot change it.
			vip: link("vip", affiliate.vip_checkout_url),
			lite: link("lite", affiliate.lite_telegram_url),
			calendly: link("calendly", affiliate.calendly_url),
		},

		// Distinct from "the affiliate hasn't filled something in": this one is
		// on the owner, so the UI shows a notice rather than a task.
		vipLinkPending: !affiliate.vip_checkout_url,

		visits: {
			today: todayVisits.count ?? 0,
			yesterday: yesterdayVisits.count ?? 0,
			last30d: recentVisits.count ?? 0,
			previous30d: priorVisits.count ?? 0,
			total: totalVisits.count ?? 0,
			byDay: [...dailyCounts.entries()]
				.map(([day, count]) => ({ day, count }))
				.sort((a, b) => a.day.localeCompare(b.day)),
		},

		onboarding: { steps, completed, total: Object.keys(steps).length },

		highlights: { days: HIGHLIGHT_DAYS, timezone, ...highlights },
	};
});

interface TrafficRow {
	sources?: { host: string | null; visits: number }[];
	countries?: { country: string; visits: number }[];
	heatmap?: { dow: number; hour: number; visits: number }[];
}

/**
 * The four "what's working" figures, from one pass over the RPC's output.
 *
 * Day and hour are aggregated separately rather than read off the single
 * busiest cell. One cell is 1/168th of the window, so on ordinary volume the
 * peak is often a coincidence — "Saturday" and "around 21:00" as independent
 * totals are both steadier and more useful than "Saturday at 21:00".
 *
 * Every field is null when there is nothing behind it, so the UI shows an
 * empty state instead of a confident-looking zero.
 */
function summarise(data: unknown) {
	const row = (data ?? {}) as TrafficRow;
	const heatmap = row.heatmap ?? [];

	const byDow = new Map<number, number>();
	const byHour = new Map<number, number>();

	for (const cell of heatmap) {
		byDow.set(cell.dow, (byDow.get(cell.dow) ?? 0) + cell.visits);
		byHour.set(cell.hour, (byHour.get(cell.hour) ?? 0) + cell.visits);
	}

	const top = <T>(entries: Map<number, number>, build: (key: number, visits: number) => T): T | null => {
		let best: { key: number; visits: number } | null = null;
		for (const [key, visits] of entries) {
			if (visits > 0 && (!best || visits > best.visits)) best = { key, visits };
		}
		return best ? build(best.key, best.visits) : null;
	};

	return {
		bestDay: top(byDow, (dow, visits) => ({ dow, visits })),
		bestHour: top(byHour, (hour, visits) => ({ hour, visits })),
		topSource: row.sources?.[0] ?? null,
		topCountry: row.countries?.[0] ?? null,
	};
}
