import type { LinkRole } from "#shared/types/affiliate";

/**
 * Everything the Overview and Links sections need, in one request.
 *
 * The affiliate is resolved from the session by requireAffiliate() and every
 * query below is filtered by that id. Nothing in this handler reads an
 * identifier from the request — see the note at the top of server/utils/auth.ts.
 */
export default defineEventHandler(async (event) => {
	const affiliate = await requireAffiliate(event);

	const today = new Date().toISOString().slice(0, 10);
	const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)
		.toISOString().slice(0, 10);

	const [todayVisits, recentVisits, totalVisits, firstVisit, byDay] = await Promise.all([
		db().from("referral_visits").select("*", { count: "exact", head: true })
			.eq("affiliate_id", affiliate.id).eq("day", today),

		db().from("referral_visits").select("*", { count: "exact", head: true })
			.eq("affiliate_id", affiliate.id).gte("day", thirtyDaysAgo),

		db().from("referral_visits").select("*", { count: "exact", head: true })
			.eq("affiliate_id", affiliate.id),

		db().from("referral_visits").select("occurred_at")
			.eq("affiliate_id", affiliate.id)
			.order("occurred_at", { ascending: true })
			.limit(1).maybeSingle(),

		db().from("referral_visits").select("day")
			.eq("affiliate_id", affiliate.id).gte("day", thirtyDaysAgo),
	]);

	// Counted in memory rather than with a group-by: PostgREST has no grouping,
	// and 30 days of unique daily visits for one affiliate is a small set.
	const dailyCounts = new Map<string, number>();
	for (const row of byDay.data ?? []) {
		const day = row.day as string;
		dailyCounts.set(day, (dailyCounts.get(day) ?? 0) + 1);
	}

	const onboarding = (affiliate.onboarding ?? {}) as Record<string, unknown>;

	// Derived from real state, not from a flag the affiliate could set. Only
	// "shared" is a recorded action, because copying a link leaves no trace.
	const steps = {
		liteTelegramAdded: Boolean(affiliate.lite_telegram_url),
		calendlyAdded: Boolean(affiliate.calendly_url),
		linkShared: onboarding.linkShared === true,
		firstVisitReceived: Boolean(firstVisit.data),
	};

	const completed = Object.values(steps).filter(Boolean).length;

	const link = (role: LinkRole, value: string | null) =>
		isAllowedLink(role, value) ? value : null;

	return {
		affiliate: {
			slug: affiliate.slug,
			displayName: affiliate.display_name,
			timezone: affiliate.timezone,
			memberSince: affiliate.created_at,
		},

		referralUrl: referralUrl(event, affiliate.slug),

		links: {
			// Generated by us from Whop during onboarding — the affiliate has no
			// field for this and cannot change it.
			vip: link("vip", affiliate.vip_checkout_url),
			lite: link("lite", affiliate.lite_telegram_url),
			calendly: link("calendly", affiliate.calendly_url),
		},

		// Distinct from "the affiliate hasn't filled something in": this one is
		// on the owner, so the UI shows a notice rather than a task.
		vipLinkPending: !affiliate.vip_checkout_url,

		visits: {
			today: todayVisits.count ?? 0,
			last30d: recentVisits.count ?? 0,
			total: totalVisits.count ?? 0,
			byDay: [...dailyCounts.entries()]
				.map(([day, count]) => ({ day, count }))
				.sort((a, b) => a.day.localeCompare(b.day)),
		},

		onboarding: { steps, completed, total: Object.keys(steps).length },
	};
});
