// This file was generated by the Storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokMultiasset, StoryblokMultilink, StoryblokRichTextDoc } from '../storyblok.d.ts';
export interface AboutUsBlockBlok {
  sub_title?: string;
  title?: string;
  text?: string;
  cards?: CardBlok[];
  anchor?: string;
  component: "aboutUs_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface AiPanelBlok {
  tab_label?: string;
  sub_title?: string;
  title?: string;
  text?: string;
  steps?: StepBlok[];
  button?: ButtonBlok[];
  video_id?: string;
  component: "ai_panel";
  _uid: string;
  _editable?: string | undefined;
}

export interface AmethystBlockBlok {
  auto_switch_seconds?: string;
  panels?: AiPanelBlok[];
  anchor?: string;
  component: "amethyst_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface BenefitBlok {
  text?: string;
  image?: StoryblokAsset;
  component: "benefit";
  _uid: string;
  _editable?: string | undefined;
}

export interface BenefitsBlockBlok {
  sub_text?: string;
  title?: string;
  sub_title?: string;
  text?: string;
  button?: ButtonBlok[];
  benefit?: {
    [k: string]: unknown;
  }[];
  anchor?: string;
  component: "benefits_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface BenefitsOverviewBlockBlok {
  sub_text?: string;
  title?: string;
  anchor?: string;
  component: "benefitsOverview_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface ButtonBlok {
  title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  variant?: "" | "primary" | "secondary" | "link";
  link_role?: "" | "''" | "vip" | "lite" | "calendly";
  component: "button";
  _uid: string;
  _editable?: string | undefined;
}

export interface CardBlok {
  title?: string;
  text?: string;
  component: "card";
  _uid: string;
  _editable?: string | undefined;
}

export interface ConfigBlok {
  header_menu?: MenuLinkBlok[];
  cta_menu?: MenuLinkBlok[];
  default_lite?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  default_calendly?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  footer_menu?: FooterMenuBlok[];
  component: "config";
  _uid: string;
  _editable?: string | undefined;
}

export interface CtaBlockBlok {
  sub_text?: string;
  title?: string;
  sub_title?: string;
  button?: ButtonBlok[];
  text?: string;
  anchor?: string;
  component: "cta_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface FaqBlockBlok {
  sub_title?: string;
  title?: string;
  text_line?: string;
  faq_item?: FaqItemBlok[];
  anchor?: string;
  component: "faq_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface FaqItemBlok {
  question_title?: string;
  answer_text?: string;
  component: "faq_item";
  _uid: string;
  _editable?: string | undefined;
}

export interface FooterMenuBlok {
  footer_image?: StoryblokAsset;
  footer_subTitle?: string;
  footer_titleLeft?: string;
  footer_linkLeft?: MenuLinkBlok[];
  footer_titleMiddle?: string;
  footer_linkMiddle?: MenuLinkBlok[];
  footer_titleRight?: string;
  footer_linkRight?: MenuLinkBlok[];
  subFooter_text?: string;
  component: "footer_menu";
  _uid: string;
  _editable?: string | undefined;
}

export interface HeroBlockBlok {
  pre_text_line?: string;
  title?: string;
  sub_title?: string;
  text?: string;
  button?: ButtonBlok[];
  anchor?: string;
  component: "hero_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface MarqueeBlockBlok {
  title?: string;
  item?: StoryblokMultiasset;
  anchor?: string;
  component: "marquee_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface MenuLinkBlok {
  label?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  link_role?: "" | "''" | "lite" | "calendly";
  component: "menu_link";
  _uid: string;
  _editable?: string | undefined;
}

export interface PageBlok {
  body?: unknown[];
  component: "page";
  _uid: string;
  _editable?: string | undefined;
}

export interface PaymentCardBlok {
  title?: string;
  price?: string;
  price_adjative?: string;
  benefit?: TextBlok[];
  Bonus_benefit?: string;
  subText_button_rich?: StoryblokRichTextDoc;
  button?: ButtonBlok[];
  component: "paymentCard";
  _uid: string;
  _editable?: string | undefined;
}

export interface PaymentPlansBlockBlok {
  sub_title?: string;
  title?: string;
  paymentCard?: PaymentCardBlok[];
  anchor?: string;
  component: "paymentPlans_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface StatisticBlok {
  count?: string;
  sub_title?: string;
  component: "statistic";
  _uid: string;
  _editable?: string | undefined;
}

export interface StatisticsBlockBlok {
  statistic?: StatisticBlok[];
  anchor?: string;
  pre_text_line?: string;
  component: "statistics_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface StepBlok {
  number?: string;
  title?: string;
  text?: string;
  component: "step";
  _uid: string;
  _editable?: string | undefined;
}

export interface TeamBlockBlok {
  sub_title?: string;
  title?: string;
  teamCard?: TeamCardBlok[];
  textCard_title?: string;
  textCard_textArea?: StoryblokRichTextDoc;
  anchor?: string;
  component: "team_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface TeamCardBlok {
  name?: string;
  sub_text?: string;
  image?: StoryblokAsset;
  positioning?: "" | "Left" | "Right";
  component: "teamCard";
  _uid: string;
  _editable?: string | undefined;
}

export interface TestimonialBlok {
  video_id?: string;
  name?: string;
  country?: (
    "" | "canada" | "usa" | "netherlands" | "germany" | "belgium" | "spain" | "france" | "england" | "portugal"
  )[];
  text?: string;
  component: "testimonial";
  _uid: string;
  _editable?: string | undefined;
}

export interface TestimonialsBlockBlok {
  pre_title?: string;
  title?: string;
  sub_title?: string;
  testimonial?: TestimonialBlok[];
  anchor?: string;
  component: "testimonials_block";
  _uid: string;
  _editable?: string | undefined;
}

export interface TextBlok {
  text?: string;
  component: "text";
  _uid: string;
  _editable?: string | undefined;
}

export interface VideoBlockBlok {
  sub_title?: string;
  title?: string;
  video_id?: string;
  anchor?: string;
  video_title?: string;
  poster_image?: StoryblokAsset;
  autoplay?: boolean;
  loop?: boolean;
  show_controls?: boolean;
  component: "video_block";
  _uid: string;
  _editable?: string | undefined;
}

export type ContentType = BenefitBlok | ConfigBlok | PageBlok;
