-- Affiliate programme — core schema.
--
-- Model: one tier. Every affiliate is a paid affiliate with a login and the
-- full dashboard. There is deliberately no `tier` column.
--
-- Money is entirely Whop's: it calculates commission, holds it 30 days and pays
-- out automatically. Nothing here stores or computes an amount.

create extension if not exists pgcrypto with schema extensions;

create type public.affiliate_status as enum ('active', 'paused', 'revoked');

-- ─────────────────────────────────────────────────────────────── helper
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ─────────────────────────────────────────────────────────── affiliates
create table public.affiliates (
  id uuid primary key default gen_random_uuid(),

  -- The public ?r= value. Lowercase, url-safe, 2-32 chars, no leading or
  -- trailing dash. Matched by SLUG_RE in server/middleware/referral.ts —
  -- keep the two in sync.
  slug text not null unique
       check (slug ~ '^[a-z0-9][a-z0-9-]{0,30}[a-z0-9]$'),
  display_name text not null check (length(display_name) between 1 and 80),

  status public.affiliate_status not null default 'active',

  -- Whop linkage. Null until an admin runs the Whop onboarding step.
  whop_affiliate_id text unique,              -- aff_xxx
  whop_username     text,                     -- the ?a= value
  whop_checkout_configuration_id text,        -- ch_xxx, carries our metadata

  -- The three swappable link roles. Each is host-constrained to match
  -- shared/utils/isAllowedLink.ts, so a bad write can never put an arbitrary
  -- URL behind a button on the public marketing site. Enforced in three
  -- places on purpose: here, at write time in the API, and at render time.
  --
  -- vip is generated by us from Whop; the other two are affiliate-supplied.
  vip_checkout_url  text check (vip_checkout_url  ~ '^https://(www\.)?whop\.com/'),
  lite_telegram_url text check (lite_telegram_url ~ '^https://(t\.me|telegram\.me)/'),
  calendly_url      text check (calendly_url      ~ '^https://(www\.)?calendly\.com/'),

  -- SET NULL, never CASCADE: deleting a login must not erase the affiliate's
  -- historical conversions and visits.
  user_id uuid unique references auth.users(id) on delete set null,

  avatar_path text,
  timezone    text not null default 'UTC',
  locale      text not null default 'en',

  -- Last time the slug changed, for the 30-day cooldown in Settings.
  slug_changed_at timestamptz,

  -- Derived onboarding progress, cached. Never trusted as the source of
  -- truth — the dashboard recomputes it from real state.
  onboarding jsonb not null default '{}'::jsonb,

  notes      text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index affiliates_active_idx  on public.affiliates (slug) where status = 'active';
create index affiliates_user_id_idx on public.affiliates (user_id);

create trigger affiliates_set_updated_at
  before update on public.affiliates
  for each row execute function public.set_updated_at();

-- Slugs that must never be handed out, because they would collide with a real
-- route or read as official. Inserted as revoked so they can never resolve.
insert into public.affiliates (slug, display_name, status) values
  ('admin',     'reserved', 'revoked'),
  ('api',       'reserved', 'revoked'),
  ('login',     'reserved', 'revoked'),
  ('dashboard', 'reserved', 'revoked'),
  ('www',       'reserved', 'revoked'),
  ('support',   'reserved', 'revoked');

-- ──────────────────────────────────────────────── affiliate_slug_aliases
-- When an affiliate changes their slug, the old one keeps resolving for a
-- grace period so links already printed on a QR code or posted in a video
-- don't die. The referral middleware checks this table too.
create table public.affiliate_slug_aliases (
  slug         text primary key
               check (slug ~ '^[a-z0-9][a-z0-9-]{0,30}[a-z0-9]$'),
  affiliate_id uuid not null references public.affiliates(id) on delete cascade,
  expires_at   timestamptz not null,
  created_at   timestamptz not null default now()
);
create index affiliate_slug_aliases_affiliate_idx
  on public.affiliate_slug_aliases (affiliate_id);

-- ────────────────────────────────────────────────────────── admin_users
-- A table rather than a JWT claim or user metadata: instantly revocable,
-- queryable, and immune to the classic mistake of trusting a field the user
-- can write to themselves.
create table public.admin_users (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- ─────────────────────────────────────────────────── affiliate_invites
-- One-time codes the owner generates and hands over out of band. The
-- plaintext is shown once at creation and never stored.
create table public.affiliate_invites (
  id           uuid primary key default gen_random_uuid(),
  affiliate_id uuid not null references public.affiliates(id) on delete cascade,

  -- hex(hmac_sha256(OTP_PEPPER, normalized_code)). The pepper lives in env,
  -- not here, so a database leak on its own does not make these reversible.
  code_hash   text not null unique,
  -- First group of the code ("4T9K"), so the owner can tell two outstanding
  -- invites apart without being able to reconstruct either.
  code_prefix text not null,

  expires_at  timestamptz not null,
  redeemed_at timestamptz,
  redeemed_ip inet,
  revoked_at  timestamptz,

  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

-- At most one live invite per affiliate. Reissuing therefore has to revoke the
-- previous one first, which is what stops old codes quietly staying valid.
create unique index affiliate_invites_one_live
  on public.affiliate_invites (affiliate_id)
  where redeemed_at is null and revoked_at is null;

-- ──────────────────────────────────────────────────────────── sessions
-- Opaque server-minted sessions. The browser holds a random token, never a
-- JWT, so XSS has no bearer token to steal and revocation is immediate
-- rather than "valid until it expires".
create table public.sessions (
  id      uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,

  token_hash text not null unique,        -- sha256(raw token), hex

  issued_at           timestamptz not null default now(),
  last_seen_at        timestamptz not null default now(),
  absolute_expires_at timestamptz not null,   -- issued_at + 30d, never extended
  idle_expires_at     timestamptz not null,   -- last_seen_at + 7d, slides
  revoked_at          timestamptz,

  user_agent text,
  ip         inet
);
create index sessions_user_idx   on public.sessions (user_id);
create index sessions_expiry_idx on public.sessions (absolute_expires_at);

-- ───────────────────────────────────────────────────────── conversions
-- The attribution table, written only by the Whop webhook.
--
-- Every row is a VIP sale. Lite (Telegram) and Calendly produce no rows
-- because nothing is sold through them.
--
-- GDPR: buyer username only. There is deliberately no column for email, real
-- name or amount, so a later refactor cannot pass them through by accident.
create table public.conversions (
  whop_payment_id text primary key,
  affiliate_id    uuid not null references public.affiliates(id) on delete cascade,
  buyer_username  text,
  status          text,
  occurred_at     timestamptz,
  -- Trimmed webhook payload for debugging. The mapper strips PII before it
  -- reaches here.
  raw        jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index conversions_affiliate_idx
  on public.conversions (affiliate_id, occurred_at desc nulls last);

-- ────────────────────────────────────────────────────── referral_visits
create table public.referral_visits (
  id           bigserial primary key,
  affiliate_id uuid not null references public.affiliates(id) on delete cascade,
  occurred_at  timestamptz not null default now(),
  day          date not null,          -- UTC, set by the app

  -- sha256(VISIT_PEPPER || ip || user_agent || day). Pseudonymous and rotates
  -- daily; no IP or user agent is ever stored. GDPR data minimisation.
  visitor_hash text not null,

  path          text,
  referrer_host text,
  country       text
);

-- One row per visitor per affiliate per day, so the metric is "unique daily
-- visits". A raw click counter would be trivially inflatable by refreshing,
-- and this is a number affiliates are judged on.
create unique index referral_visits_dedupe
  on public.referral_visits (affiliate_id, visitor_hash, day);
create index referral_visits_day_idx
  on public.referral_visits (affiliate_id, day desc);

-- ─────────────────────────────────────────────────────── notifications
create table public.notifications (
  id           bigserial primary key,
  affiliate_id uuid not null references public.affiliates(id) on delete cascade,
  kind         text not null,
  payload      jsonb not null default '{}'::jsonb,
  read_at      timestamptz,
  created_at   timestamptz not null default now()
);
create index notifications_inbox_idx
  on public.notifications (affiliate_id, created_at desc);

-- ────────────────────────────────────────────────────────── rate_limits
create table public.rate_limits (
  bucket       text primary key,
  window_start timestamptz not null default now(),
  count        int not null default 0,
  locked_until timestamptz
);

-- ─────────────────────────────────────────────────── whop_stats_cache
-- Durable stale-while-error store. When Whop is unreachable the dashboard
-- shows the last good figures with a timestamp, never a spinner and never
-- zeroes — zeroes read as "you earned nothing" and cause panic.
create table public.whop_stats_cache (
  affiliate_id uuid primary key references public.affiliates(id) on delete cascade,
  fetched_at   timestamptz not null default now(),
  ok           boolean not null default true,
  last_error   text,
  payload      jsonb not null
);

-- ──────────────────────────────────────────────────────── gdpr_requests
create table public.gdpr_requests (
  id           uuid primary key default gen_random_uuid(),
  affiliate_id uuid not null references public.affiliates(id) on delete cascade,
  kind         text not null check (kind in ('export', 'delete')),
  status       text not null default 'pending'
               check (status in ('pending', 'ready', 'completed', 'cancelled')),
  -- Deletions sit in a grace period so an accidental or coerced request can
  -- be undone before anything is destroyed.
  execute_after timestamptz,
  completed_at  timestamptz,
  created_at    timestamptz not null default now()
);
create index gdpr_requests_affiliate_idx
  on public.gdpr_requests (affiliate_id, created_at desc);

-- ─────────────────────────────────────────────────────────── audit_log
-- MUST NEVER contain an invite code, password, or session token. Enforced by
-- convention in server/utils/audit.ts, which never receives them.
create table public.audit_log (
  id                   bigserial primary key,
  at                   timestamptz not null default now(),
  actor_user_id        uuid references auth.users(id) on delete set null,
  actor_kind           text not null check (actor_kind in ('admin', 'affiliate', 'system')),
  action               text not null,
  subject_affiliate_id uuid references public.affiliates(id) on delete set null,
  ip                   inet,
  user_agent           text,
  meta                 jsonb not null default '{}'::jsonb
);
create index audit_log_at_idx      on public.audit_log (at desc);
create index audit_log_subject_idx on public.audit_log (subject_affiliate_id, at desc);
